const d3CountryToIso = {
	Afghanistan: 'af',
	Albania: 'al',
	Algeria: 'dz',
	Angola: 'ao',
	Argentina: 'ar',
	Armenia: 'am',
	Australia: 'au',
	Austria: 'at',
	Azerbaijan: 'az',
	Bangladesh: 'bd',
	Belarus: 'by',
	Belgium: 'be',
	Belize: 'bz',
	Benin: 'bj',
	Bhutan: 'bt',
	Bolivia: 'bo',
	'Bosnia and Herzegovina': 'ba',
	Botswana: 'bw',
	Brazil: 'br',
	Brunei: 'bn',
	Bulgaria: 'bg',
	'Burkina Faso': 'bf',
	Burundi: 'bi',
	Cambodia: 'kh',
	Cameroon: 'cm',
	Canada: 'ca',
	'Central African Republic': 'cf',
	Chad: 'td',
	Chile: 'cl',
	China: 'cn',
	Colombia: 'co',
	'Costa Rica': 'cr',
	Croatia: 'hr',
	Cuba: 'cu',
	Cyprus: 'cy',
	'Czech Republic': 'cz',
	Denmark: 'dk',
	Djibouti: 'dj',
	'Dominican Republic': 'do',
	Ecuador: 'ec',
	Egypt: 'eg',
	'El Salvador': 'sv',
	Eritrea: 'er',
	Estonia: 'ee',
	Ethiopia: 'et',
	'Falkland Islands': 'fk',
	Fiji: 'fj',
	Finland: 'fi',
	France: 'fr',
	Gabon: 'ga',
	Gambia: 'gm',
	Georgia: 'ge',
	Germany: 'de',
	Ghana: 'gh',
	Greece: 'gr',
	Greenland: 'gl',
	Guatemala: 'gt',
	Guinea: 'gn',
	Guyana: 'gy',
	Haiti: 'ht',
	Honduras: 'hn',
	Hungary: 'hu',
	Iceland: 'is',
	India: 'in',
	Indonesia: 'id',
	Iran: 'ir',
	Iraq: 'iq',
	Ireland: 'ie',
	Israel: 'il',
	Italy: 'it',
	Jamaica: 'jm',
	Japan: 'jp',
	Jordan: 'jo',
	Kazakhstan: 'kz',
	Kenya: 'ke',
	Kuwait: 'kw',
	Kyrgyzstan: 'kg',
	Laos: 'la',
	Latvia: 'lv',
	Lebanon: 'lb',
	Lesotho: 'ls',
	Liberia: 'lr',
	Libya: 'ly',
	Lithuania: 'lt',
	Luxembourg: 'lu',
	Madagascar: 'mg',
	Malawi: 'mw',
	Malaysia: 'my',
	Mali: 'ml',
	Malta: 'mt',
	Mauritania: 'mr',
	Mauritius: 'mu',
	Mexico: 'mx',
	Moldova: 'md',
	Mongolia: 'mn',
	Montenegro: 'me',
	Morocco: 'ma',
	Mozambique: 'mz',
	Myanmar: 'mm',
	Namibia: 'na',
	Nepal: 'np',
	Netherlands: 'nl',
	'New Caledonia': 'nc',
	'New Zealand': 'nz',
	Nicaragua: 'ni',
	Niger: 'ne',
	'North Korea': 'kp',
	Macedonia: 'mk',
	Norway: 'no',
	Oman: 'om',
	Pakistan: 'pk',
	Panama: 'pa',
	Paraguay: 'py',
	Peru: 'pe',
	Philippines: 'ph',
	Poland: 'pl',
	Portugal: 'pt',
	'Puerto Rico': 'pr',
	Qatar: 'qa',
	'Republic of Serbia': 'rs',
	Romania: 'ro',
	Russia: 'ru',
	Rwanda: 'rw',
	'Saudi Arabia': 'sa',
	Senegal: 'sn',
	'Sierra Leone': 'sl',
	Slovakia: 'sk',
	Slovenia: 'si',
	'Solomon Islands': 'sb',
	'South Africa': 'za',
	'South Korea': 'kr',
	Spain: 'es',
	'Sri Lanka': 'lk',
	Sudan: 'sd',
	Suriname: 'sr',
	Sweden: 'se',
	Switzerland: 'ch',
	Syria: 'sy',
	Taiwan: 'tw',
	Tajikistan: 'tj',
	'United Republic of Tanzania': 'tz',
	Thailand: 'th',
	'Trinidad and Tobago': 'tt',
	Tunisia: 'tn',
	Turkmenistan: 'tm',
	Uganda: 'ug',
	Ukraine: 'ua',
	'United Arab Emirates': 'ae',
	USA: 'us',
	Uruguay: 'uy',
	Uzbekistan: 'uz',
	Vanuatu: 'vu',
	Venezuela: 've',
	Vietnam: 'vn',
	Yemen: 'ye',
	Zambia: 'zm',
	Zimbabwe: 'zw',
};

export {
	d3CountryToIso,
};
