master:
  hostname: "easydam.rt.gw"
  user: "root"
  deploy_path: "/opt/easyengine/sites/easydam.rt.gw/app/htdocs/plugin"
develop:
  hostname: "easydam-dev.rt.gw"
  user: "root"
  deploy_path: "/opt/easyengine/sites/easydam-dev.rt.gw/app/htdocs/plugin"
