<?php
/**
 * WooCommerce Integration Helper Functions
 *
 * Utility functions for the WooCommerce integration module.
 *
 * @package GoDAM
 * @since 1.5.0
 */

defined( 'ABSPATH' ) || exit;

/**
 * Get safe asset version with fallback handling.
 *
 * Returns the modification time of the asset file, or falls back to
 * the version defined in the accompanying .asset.php file, or current
 * timestamp if neither exist.
 *
 * This prevents PHP warnings when filemtime() is called on non-existent files
 * during development or when build files are missing.
 *
 * @since 1.5.0
 *
 * @param string $filepath Full path to the asset file.
 * @return int|string Version number or timestamp.
 */
function rtgodam_wc_get_asset_version( $filepath ) {
	// Try direct file check first.
	if ( file_exists( $filepath ) ) {
		return filemtime( $filepath );
	}

	// Fallback to .asset.php file (generated by webpack).
	$asset_file = str_replace( array( '.min.js', '.min.css' ), '.asset.php', $filepath );

	if ( file_exists( $asset_file ) ) {
		$asset = include $asset_file; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable -- Safe: path is plugin-controlled.
		if ( is_array( $asset ) && isset( $asset['version'] ) ) {
			return $asset['version'];
		}
	}

	// Last resort: return current timestamp.
	return time();
}
