/**
 * External dependencies
 */
import { useDispatch, useSelector } from 'react-redux';

/**
 * WordPress dependencies
 */
import { ToggleControl, TextControl } from '@wordpress/components';
import { __ } from '@wordpress/i18n';

/**
 * Internal dependencies
 */
import { updateMediaSetting } from '../../redux/slice/media-settings';
import GodamPanel from '../../common/GodamPanel.jsx';

const VideoThumbnails = () => {
	const dispatch = useDispatch();

	const videoThumbnails = useSelector( ( state ) => state.mediaSettings.video.video_thumbnails ) || 5;
	const overwriteThumbnails = useSelector( ( state ) => state.mediaSettings.video.overwrite_thumbnails ) || false;

	const setVideoThumbnails = ( value ) => {
		value = parseInt( value, 10 );

		if ( value >= 0 && value <= 10 ) {
			dispatch( updateMediaSetting( { category: 'video', key: 'video_thumbnails', value } ) );
		}
	};

	return (
		<GodamPanel
			heading={ __( 'Video Thumbnails', 'godam' ) }
			isPremiumFeature={ true }
		>
			<div>
				<label className="easydam-settings-label" htmlFor="video_thumbnails_count">
					{ __( 'Number of video thumbnails generated', 'godam' ) }
				</label>
				<TextControl
					className="godam-input"
					type="number"
					min="1"
					max="10"
					value={ videoThumbnails }
					onChange={ ( value ) => setVideoThumbnails( value ) }
					help={ __( `This field specifies the number of video thumbnails that will be generated by the GoDAM. To choose from the generated thumbnails for a video, go to Media > Edit > Video Thumbnails. Thumbnails are only generated when the video is first uploaded. Please enter a value between 1 and 10`, 'godam' ) }
				/>
			</div>

			<div className="mt-4">
				<ToggleControl
					__nextHasNoMarginBottom
					className="godam-toggle"
					label="Over-write video thumbnails"
					checked={ overwriteThumbnails }
					onChange={ ( value ) =>
						dispatch( updateMediaSetting( {
							category: 'video',
							key: 'overwrite_thumbnails',
							value,
						} ) )
					}
					help={ __( 'If enabled, GoDAM will replace existing media thumbnails with regenerated ones after retranscoding. If disabled, media thumbnails will remain untouched', 'godam' ) }
				/>
			</div>

		</GodamPanel>
	);
};

export default VideoThumbnails;
